### ISSUE TITLE
Cannot enable app

### ISSUE THREAD

**Issue by Huster-at-github** [GluuFederation/nextcloud-oxd-plugin#3]
Get this error: "App with id gluusso has invalid signature"

**Comment by willow9886** [comment]
Can you provide more details and possibly screenshots so we can reproduce?

**Comment by Huster-at-github** [comment]
Strange ..... just wanted to reproduce this bug but now it's working:

- Can enable app in Apps
- Can open config page
- Cannot test because no OpenID available just now

Thanks for your attention. You can close this bug.

**Comment by willow9886** [comment]
@Huster-at-github regarding 

> Cannot test because no OpenID available just now

You can simply use Google if you don't have another OpenID Connect Provider available...

**Comment by nynymike** [comment]
@Huster-at-github  Or just deploy a Gluu Server, it's really easy. Install the package and run setup... see https://gluu.org/docs/ce/3.0.1/installation-guide/install/
