### ISSUE TITLE
Auth Error: Missing claim : (email). Please talk to your organizational system administrator.

### ISSUE THREAD

**Issue by nikdavnik** [GluuFederation/nextcloud-oxd-plugin#6]
I am getting **Missing claim : (email). Please talk to your organizational system administrator.** error while trying to auth via nextcloud-oxd-plugin

test user in gluu server have email atribute:
email scope is required (by default) in nextcloud-oxd-plugin
(please see attached images)
![pic3](https://user-images.githubusercontent.com/17772064/36687293-9366b964-1b42-11e8-833f-cee40148a93b.png)
![pic](https://user-images.githubusercontent.com/17772064/36687317-a2f02dd4-1b42-11e8-898e-abfde89d260d.png)
![pic2](https://user-images.githubusercontent.com/17772064/36687328-a5dfb712-1b42-11e8-9d1d-e48a28109dad.png)

gluu server: gluu-server-3.1.2 on ubuntu 16.04
odx-server: on ubuntu 16.04 
nextcloud: 11.0.1

**Comment by nynymike** [comment]
1. Can you provide LDIF of the entry under `ou=clients,o=(org-inum),o=gluu` ? Have you released the `email` scope to this client?

**Comment by nikdavnik** [comment]
After enabling email scope availale for dynamic registration its worked.
Thanks @nynymike . Will close the issue.
